package analyze

// secretRules is the TRACE secret-detection catalog: one rule per credential
// shape, each with a cheap substring pre-filter, an entropy floor and a
// severity. It mirrors RULES in analyzer/secret_detector.py.
var secretRules = []SecretRule{
	{
		ID:          "openai_legacy",
		Description: "OpenAI API key (legacy shape)",
		Regex:       "sk-[A-Za-z0-9]{20,}",
		Severity:    "critical",
		Prefix:      "sk-",
		MinEntropy:  3.0,
	},
	{
		ID:           "openai_project",
		Description:  "OpenAI project API key",
		Regex:        "sk-proj-[A-Za-z0-9_-]{20,}",
		Severity:     "critical",
		Prefix:       "sk-proj-",
		StrongPrefix: true,
	},
	{
		ID:           "anthropic",
		Description:  "Anthropic API key",
		Regex:        "sk-ant-api[A-Za-z0-9_-]{10,}",
		Severity:     "critical",
		Prefix:       "sk-ant-api",
		StrongPrefix: true,
	},
	{
		ID:          "xai",
		Description: "xAI API key",
		Regex:       "xai-[A-Za-z0-9_-]{20,}",
		Severity:    "critical",
		Prefix:      "xai-",
		MinEntropy:  3.0,
	},
	{
		ID:          "google_ai",
		Description: "Google AI / Gemini API key",
		Regex:       "AIza[0-9A-Za-z_-]{35}",
		Severity:    "high",
		Prefix:      "AIza",
		MinEntropy:  3.0,
	},
	{
		ID:           "huggingface",
		Description:  "HuggingFace access token",
		Regex:        "hf_[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "hf_",
		StrongPrefix: true,
	},
	{
		ID:          "deepseek",
		Description: "DeepSeek API key",
		Regex:       "sk-[a-f0-9]{32,}",
		Severity:    "critical",
		Prefix:      "sk-",
		MinEntropy:  3.0,
	},
	{
		ID:          "mistral",
		Description: "Mistral API key",
		Regex:       "[A-Za-z0-9]{32}\\.[A-Za-z0-9]{6}\\.[A-Za-z0-9]{6,}",
		Severity:    "critical",
		MinEntropy:  3.5,
	},
	{
		ID:          "cohere",
		Description: "Cohere API key",
		Regex:       "[A-Za-z0-9]{40}",
		Severity:    "high",
		MinEntropy:  4.0,
	},
	{
		ID:           "replicate",
		Description:  "Replicate API token",
		Regex:        "r8_[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "r8_",
		StrongPrefix: true,
	},
	{
		ID:           "together",
		Description:  "Together AI API key",
		Regex:        "tgp_[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "tgp_",
		StrongPrefix: true,
	},
	{
		ID:           "groq",
		Description:  "Groq API key",
		Regex:        "gsk_[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "gsk_",
		StrongPrefix: true,
	},
	{
		ID:           "perplexity",
		Description:  "Perplexity API key",
		Regex:        "pplx-[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "pplx-",
		StrongPrefix: true,
	},
	{
		ID:           "openrouter",
		Description:  "OpenRouter API key",
		Regex:        "sk-or-v1-[A-Za-z0-9]{20,}",
		Severity:     "critical",
		Prefix:       "sk-or-v1-",
		StrongPrefix: true,
	},
	{
		ID:           "ollama",
		Description:  "Ollama API key",
		Regex:        "ollama_[A-Za-z0-9]{20,}",
		Severity:     "high",
		Prefix:       "ollama_",
		StrongPrefix: true,
	},
	{
		ID:           "github_pat",
		Description:  "GitHub personal access token (classic)",
		Regex:        "ghp_[A-Za-z0-9]{36,}",
		Severity:     "critical",
		Prefix:       "ghp_",
		StrongPrefix: true,
	},
	{
		ID:           "github_fine",
		Description:  "GitHub fine-grained PAT",
		Regex:        "github_pat_[A-Za-z0-9_]{20,}",
		Severity:     "critical",
		Prefix:       "github_pat_",
		StrongPrefix: true,
	},
	{
		ID:           "github_oauth",
		Description:  "GitHub OAuth token",
		Regex:        "gho_[A-Za-z0-9]{36,}",
		Severity:     "high",
		Prefix:       "gho_",
		StrongPrefix: true,
	},
	{
		ID:           "github_app",
		Description:  "GitHub app/user token",
		Regex:        "ghu_[A-Za-z0-9]{36,}|ghs_[A-Za-z0-9]{36,}|ghr_[A-Za-z0-9]{36,}",
		Severity:     "high",
		Prefix:       "gh",
		StrongPrefix: true,
	},
	{
		ID:           "gitlab_pat",
		Description:  "GitLab personal access token",
		Regex:        "glpat-[A-Za-z0-9_-]{20,}",
		Severity:     "critical",
		Prefix:       "glpat-",
		StrongPrefix: true,
	},
	{
		ID:           "bitbucket",
		Description:  "Bitbucket app password",
		Regex:        "ATBB[A-Za-z0-9]{32,}",
		Severity:     "critical",
		Prefix:       "ATBB",
		StrongPrefix: true,
	},
	{
		ID:           "aws_access_key",
		Description:  "AWS access key ID",
		Regex:        "AKIA[0-9A-Z]{16}",
		Severity:     "critical",
		Prefix:       "AKIA",
		StrongPrefix: true,
	},
	{
		ID:           "aws_temp",
		Description:  "AWS temporary access key ID",
		Regex:        "ASIA[0-9A-Z]{16}",
		Severity:     "critical",
		Prefix:       "ASIA",
		StrongPrefix: true,
	},
	{
		ID:          "azure",
		Description: "Azure client secret / connection string",
		Regex:       "(?i)(?:azure|tenant|subscription|client[_-]?secret)[_-]?(?:key|id|secret)\\s*[:=]\\s*[\\\"']?[a-zA-Z0-9\\-_.]{20,}",
		Severity:    "critical",
		Prefix:      "azure",
		MinEntropy:  3.0,
	},
	{
		ID:          "gcp_service_account",
		Description: "GCP service account key",
		Regex:       "\\\"type\\\"\\s*:\\s*\\\"service_account\\\"",
		Severity:    "high",
		Prefix:      "service_account",
	},
	{
		ID:           "stripe",
		Description:  "Stripe secret/restricted key",
		Regex:        "sk_live_[0-9a-zA-Z]{24,}|sk_test_[0-9a-zA-Z]{24,}|rk_live_[0-9a-zA-Z]{24,}|rk_test_[0-9a-zA-Z]{24,}",
		Severity:     "critical",
		Prefix:       "sk_",
		StrongPrefix: true,
	},
	{
		ID:           "slack_bot",
		Description:  "Slack bot token",
		Regex:        "xoxb-[0-9A-Za-z-]{50,}",
		Severity:     "high",
		Prefix:       "xoxb-",
		StrongPrefix: true,
	},
	{
		ID:           "slack_user",
		Description:  "Slack user token",
		Regex:        "xoxp-[0-9A-Za-z-]{50,}",
		Severity:     "high",
		Prefix:       "xoxp-",
		StrongPrefix: true,
	},
	{
		ID:           "slack_app",
		Description:  "Slack app-level token",
		Regex:        "xoxa-[0-9A-Za-z-]{50,}",
		Severity:     "high",
		Prefix:       "xoxa-",
		StrongPrefix: true,
	},
	{
		ID:          "slack_webhook",
		Description: "Slack incoming webhook URL",
		Regex:       "https://hooks\\.slack\\.com/services/[A-Za-z0-9/]+",
		Severity:    "medium",
		Prefix:      "hooks.slack.com",
	},
	{
		ID:          "discord_bot",
		Description: "Discord bot token",
		Regex:       "[MN][A-Za-z0-9]{23,}\\.[A-Za-z0-9_-]{6}\\.[A-Za-z0-9_-]{27,}",
		Severity:    "high",
		MinEntropy:  3.5,
	},
	{
		ID:           "npm_token",
		Description:  "npm access token",
		Regex:        "npm_[A-Za-z0-9]{36,}",
		Severity:     "high",
		Prefix:       "npm_",
		StrongPrefix: true,
	},
	{
		ID:           "pypi_token",
		Description:  "PyPI API token",
		Regex:        "pypi-[A-Za-z0-9_-]{50,}",
		Severity:     "high",
		Prefix:       "pypi-",
		StrongPrefix: true,
	},
	{
		ID:          "nuget",
		Description: "NuGet API key",
		Regex:       "oy2[a-z0-9]{15,}[A-Za-z0-9]{28}",
		Severity:    "high",
		Prefix:      "oy2",
		MinEntropy:  4.0,
	},
	{
		ID:           "atlassian",
		Description:  "Atlassian Cloud API token",
		Regex:        "ATATT3[A-Za-z0-9+/=]{20,}",
		Severity:     "critical",
		Prefix:       "ATATT3",
		StrongPrefix: true,
	},
	{
		ID:           "shopify",
		Description:  "Shopify access token",
		Regex:        "shpat_[A-Za-z0-9]{32,}|shpca_[A-Za-z0-9]{32,}|shpss_[A-Za-z0-9]{32,}",
		Severity:     "critical",
		Prefix:       "shp",
		StrongPrefix: true,
	},
	{
		ID:           "sendgrid",
		Description:  "SendGrid API key",
		Regex:        "SG\\.[A-Za-z0-9_-]{20,}\\.[A-Za-z0-9_-]{20,}",
		Severity:     "high",
		Prefix:       "SG.",
		StrongPrefix: true,
	},
	{
		ID:          "twilio",
		Description: "Twilio API key",
		Regex:       "SK[0-9a-fA-F]{32}",
		Severity:    "high",
		Prefix:      "SK",
		MinEntropy:  3.0,
	},
	{
		ID:          "telegram_bot",
		Description: "Telegram bot token",
		Regex:       "[0-9]{8,10}:[A-Za-z0-9_-]{35}",
		Severity:    "high",
		MinEntropy:  3.5,
	},
	{
		ID:          "jwt",
		Description: "JSON Web Token",
		Regex:       "eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}",
		Severity:    "high",
		Prefix:      "eyJ",
		MinEntropy:  3.0,
	},
	{
		ID:           "private_key_pem",
		Description:  "PEM private key block",
		Regex:        "-----BEGIN\\s+(?:RSA\\s+|EC\\s+|DSA\\s+)?PRIVATE\\s+KEY-----",
		Severity:     "critical",
		Prefix:       "PRIVATE KEY",
		StrongPrefix: true,
	},
	{
		ID:           "private_key_openssh",
		Description:  "OpenSSH private key block",
		Regex:        "-----BEGIN\\s+OPENSSH\\s+PRIVATE\\s+KEY-----",
		Severity:     "critical",
		Prefix:       "OPENSSH PRIVATE KEY",
		StrongPrefix: true,
	},
	{
		ID:           "pgp_private_key",
		Description:  "PGP private key block",
		Regex:        "-----BEGIN\\s+PGP\\s+PRIVATE\\s+KEY\\s+BLOCK-----",
		Severity:     "critical",
		Prefix:       "PGP PRIVATE KEY",
		StrongPrefix: true,
	},
	{
		ID:          "generic_key",
		Description: "Generic API key (key- prefix)",
		Regex:       "\\bkey-[A-Za-z0-9_-]{10,}\\b",
		Severity:    "high",
		Prefix:      "key-",
		MinEntropy:  3.0,
	},
	{
		ID:           "databricks",
		Description:  "Databricks API token",
		Regex:        "\\bdapi[a-f0-9]{32}(?:-\\d)?\\b",
		Severity:     "critical",
		Prefix:       "dapi",
		StrongPrefix: true,
	},
	{
		ID:           "digitalocean_pat",
		Description:  "DigitalOcean personal access token",
		Regex:        "\\bdop_v1_[a-f0-9]{64}\\b",
		Severity:     "critical",
		Prefix:       "dop_v1_",
		StrongPrefix: true,
	},
	{
		ID:           "doppler",
		Description:  "Doppler API token",
		Regex:        "\\bdp\\.pt\\.[a-z0-9]{43}\\b",
		Severity:     "critical",
		Prefix:       "dp.pt.",
		StrongPrefix: true,
	},
	{
		ID:           "linear",
		Description:  "Linear API key",
		Regex:        "\\blin_api_[a-z0-9]{40}\\b",
		Severity:     "critical",
		Prefix:       "lin_api_",
		StrongPrefix: true,
	},
	{
		ID:           "notion",
		Description:  "Notion API token",
		Regex:        "\\bntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3}\\b",
		Severity:     "critical",
		Prefix:       "ntn_",
		StrongPrefix: true,
	},
	{
		ID:           "postman",
		Description:  "Postman API token",
		Regex:        "\\bPMAK-[a-f0-9]{24}-[a-f0-9]{34}\\b",
		Severity:     "critical",
		Prefix:       "PMAK-",
		StrongPrefix: true,
	},
	{
		ID:           "pulumi",
		Description:  "Pulumi API token",
		Regex:        "\\bpul-[a-f0-9]{40}\\b",
		Severity:     "critical",
		Prefix:       "pul-",
		StrongPrefix: true,
	},
	{
		ID:           "readme",
		Description:  "ReadMe API token",
		Regex:        "\\brdme_[a-z0-9]{70}\\b",
		Severity:     "critical",
		Prefix:       "rdme_",
		StrongPrefix: true,
	},
	{
		ID:           "rubygems",
		Description:  "RubyGems API token",
		Regex:        "\\brubygems_[a-f0-9]{48}\\b",
		Severity:     "critical",
		Prefix:       "rubygems_",
		StrongPrefix: true,
	},
	{
		ID:           "sendinblue",
		Description:  "Sendinblue API token",
		Regex:        "\\bxkeysib-[a-f0-9]{64}-[a-z0-9]{16}\\b",
		Severity:     "critical",
		Prefix:       "xkeysib-",
		StrongPrefix: true,
	},
	{
		ID:           "square",
		Description:  "Square access token",
		Regex:        "\\b(?:EAAA|sq0atp-)[\\w-]{22,60}\\b",
		Severity:     "critical",
		Prefix:       "sq0atp-",
		StrongPrefix: true,
	},
	{
		ID:           "typeform",
		Description:  "Typeform API token",
		Regex:        "\\btfp_[a-z0-9\\-_\\.=]{59}\\b",
		Severity:     "critical",
		Prefix:       "tfp_",
		StrongPrefix: true,
	},
	{
		ID:           "vault_batch",
		Description:  "HashiCorp Vault batch token",
		Regex:        "\\bhvb\\.[\\w-]{138,300}\\b",
		Severity:     "critical",
		Prefix:       "hvb.",
		StrongPrefix: true,
	},
	{
		ID:           "yandex",
		Description:  "Yandex API key",
		Regex:        "\\bAQVN[A-Za-z0-9_\\-]{35,38}\\b",
		Severity:     "critical",
		Prefix:       "AQVN",
		StrongPrefix: true,
	},
	{
		ID:           "maxmind",
		Description:  "MaxMind license key",
		Regex:        "\\b[A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk\\b",
		Severity:     "high",
		Prefix:       "_mmk",
		StrongPrefix: true,
	},
	{
		ID:           "octopus",
		Description:  "Octopus Deploy API key",
		Regex:        "\\bAPI-[A-Z0-9]{26}\\b",
		Severity:     "critical",
		Prefix:       "API-",
		StrongPrefix: true,
	},
	{
		ID:           "sourcegraph",
		Description:  "Sourcegraph access token",
		Regex:        "\\bsgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}\\b",
		Severity:     "critical",
		Prefix:       "sgp_",
		StrongPrefix: true,
	},
	{
		ID:           "sonar",
		Description:  "SonarQube token",
		Regex:        "\\b(?:squ_|sqp_|sqa_)[a-z0-9=_\\-]{40}\\b",
		Severity:     "high",
		Prefix:       "sq",
		StrongPrefix: true,
	},
	{
		ID:           "newrelic",
		Description:  "New Relic user API key",
		Regex:        "\\bNRAK-[a-z0-9]{27}\\b",
		Severity:     "critical",
		Prefix:       "NRAK-",
		StrongPrefix: true,
	},
	{
		ID:           "grafana",
		Description:  "Grafana API key",
		Regex:        "\\beyJrIjoi[A-Za-z0-9]{70,400}={0,3}\\b",
		Severity:     "critical",
		Prefix:       "eyJrIjoi",
		StrongPrefix: true,
	},
	{
		ID:           "hashicorp_tf",
		Description:  "HashiCorp Terraform API token",
		Regex:        "\\b[a-z0-9]{14}\\.atlasv1\\.[a-z0-9\\-_=]{60,70}\\b",
		Severity:     "critical",
		Prefix:       "atlasv1",
		StrongPrefix: true,
	},
	{
		ID:           "flyio",
		Description:  "Fly.io access token",
		Regex:        "\\b(?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+/]{100,}={0,3}|fm2_[a-zA-Z0-9+/]{100,}={0,3})\\b",
		Severity:     "critical",
		Prefix:       "fo1_",
		StrongPrefix: true,
	},
	{
		ID:          "microsoft_teams_webhook",
		Description: "Microsoft Teams webhook URL",
		Regex:       "https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9-]+@[a-z0-9-]+/IncomingWebhook/[a-z0-9]{32}/[a-z0-9-]+",
		Severity:    "medium",
		Prefix:      "webhook.office.com",
	},
	{
		ID:          "kubernetes_secret",
		Description: "Kubernetes Secret manifest",
		Regex:       "(?i)\\bkind:\\s*[\\\"']?Secret[\\\"']?(?s:.{0,200}?)\\bdata:",
		Severity:    "high",
		Prefix:      "kind: Secret",
	},
	{
		ID:           "github_refresh",
		Description:  "GitHub refresh token",
		Regex:        "\\bghr_[0-9a-zA-Z]{36}\\b",
		Severity:     "critical",
		Prefix:       "ghr_",
		StrongPrefix: true,
	},
	{
		ID:           "gitlab_ptt",
		Description:  "GitLab pipeline trigger token",
		Regex:        "\\bglptt-[a-zA-Z0-9_-]{20,}\\b",
		Severity:     "high",
		Prefix:       "glptt-",
		StrongPrefix: true,
	},
	{
		ID:           "gitlab_runner",
		Description:  "GitLab runner auth token",
		Regex:        "\\bglrt-[a-zA-Z0-9_-]{20,}\\b",
		Severity:     "high",
		Prefix:       "glrt-",
		StrongPrefix: true,
	},
	{
		ID:          "cloudflare",
		Description: "Cloudflare API key",
		Regex:       "(?i)\\b(?:cloudflare)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9_-]{40})\\b",
		Severity:    "critical",
		Prefix:      "cloudflare",
		MinEntropy:  3.0,
	},
	{
		ID:          "datadog",
		Description: "Datadog API key",
		Regex:       "(?i)\\b(?:datadog)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{40})\\b",
		Severity:    "critical",
		Prefix:      "datadog",
		MinEntropy:  3.0,
	},
	{
		ID:          "mailchimp",
		Description: "Mailchimp API key",
		Regex:       "(?i)\\b(?:mailchimp)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)\\b",
		Severity:    "critical",
		Prefix:      "mailchimp",
		MinEntropy:  3.0,
	},
	{
		ID:          "mapbox",
		Description: "Mapbox API token",
		Regex:       "\\bpk\\.[a-z0-9]{60}\\.[a-z0-9]{22}\\b",
		Severity:    "high",
		Prefix:      "pk.",
		MinEntropy:  3.0,
	},
	{
		ID:          "heroku",
		Description: "Heroku API key",
		Regex:       "(?i)\\b(?:heroku)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\b",
		Severity:    "critical",
		Prefix:      "heroku",
		MinEntropy:  3.0,
	},
	{
		ID:          "facebook",
		Description: "Facebook access token",
		Regex:       "\\b\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40}\\b",
		Severity:    "high",
		MinEntropy:  3.5,
	},
	{
		ID:          "twitch",
		Description: "Twitch API token",
		Regex:       "(?i)\\b(?:twitch)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{30})\\b",
		Severity:    "high",
		Prefix:      "twitch",
		MinEntropy:  3.0,
	},
	{
		ID:          "twitter_bearer",
		Description: "Twitter/X bearer token",
		Regex:       "(?i)\\b(?:twitter)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})\\b",
		Severity:    "critical",
		Prefix:      "twitter",
		MinEntropy:  3.0,
	},
	{
		ID:          "sentry",
		Description: "Sentry access token",
		Regex:       "(?i)\\b(?:sentry)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-f0-9]{64})\\b",
		Severity:    "critical",
		Prefix:      "sentry",
		MinEntropy:  3.0,
	},
	{
		ID:          "jfrog",
		Description: "JFrog API key",
		Regex:       "(?i)\\b(?:jfrog|artifactory|bintray|xray)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{73})\\b",
		Severity:    "critical",
		Prefix:      "jfrog",
		MinEntropy:  3.0,
	},
	{
		ID:          "dropbox",
		Description: "Dropbox API token",
		Regex:       "(?i)\\b(?:dropbox)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{15})\\b",
		Severity:    "high",
		Prefix:      "dropbox",
		MinEntropy:  3.0,
	},
	{
		ID:          "airtable",
		Description: "Airtable API key",
		Regex:       "(?i)\\b(?:airtable)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{17})\\b",
		Severity:    "high",
		Prefix:      "airtable",
		MinEntropy:  3.0,
	},
	{
		ID:          "algolia",
		Description: "Algolia API key",
		Regex:       "(?i)\\b(?:algolia)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{32})\\b",
		Severity:    "high",
		Prefix:      "algolia",
		MinEntropy:  3.0,
	},
	{
		ID:          "intercom",
		Description: "Intercom API key",
		Regex:       "(?i)\\b(?:intercom)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{60})\\b",
		Severity:    "critical",
		Prefix:      "intercom",
		MinEntropy:  3.0,
	},
	{
		ID:          "launchdarkly",
		Description: "LaunchDarkly access token",
		Regex:       "(?i)\\b(?:launchdarkly)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{40})\\b",
		Severity:    "critical",
		Prefix:      "launchdarkly",
		MinEntropy:  3.0,
	},
	{
		ID:          "netlify",
		Description: "Netlify access token",
		Regex:       "(?i)\\b(?:netlify)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{40,46})\\b",
		Severity:    "critical",
		Prefix:      "netlify",
		MinEntropy:  3.0,
	},
	{
		ID:          "plaid",
		Description: "Plaid secret key",
		Regex:       "(?i)\\b(?:plaid)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{30})\\b",
		Severity:    "critical",
		Prefix:      "plaid",
		MinEntropy:  3.0,
	},
	{
		ID:          "zendesk",
		Description: "Zendesk secret key",
		Regex:       "(?i)\\b(?:zendesk)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{40})\\b",
		Severity:    "critical",
		Prefix:      "zendesk",
		MinEntropy:  3.0,
	},
	{
		ID:          "okta",
		Description: "Okta access token",
		Regex:       "(?i)\\b(?:okta)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}(00[\\w=\\-]{40})\\b",
		Severity:    "critical",
		Prefix:      "okta",
		MinEntropy:  3.0,
	},
	{
		ID:          "sumologic",
		Description: "SumoLogic access ID",
		Regex:       "(?i)\\b(?:sumo)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}(su[a-zA-Z0-9]{12})\\b",
		Severity:    "high",
		Prefix:      "sumo",
		MinEntropy:  3.0,
	},
	{
		ID:          "travisci",
		Description: "Travis CI access token",
		Regex:       "(?i)\\b(?:travis)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{22})\\b",
		Severity:    "high",
		Prefix:      "travis",
		MinEntropy:  3.0,
	},
	{
		ID:          "mattermost",
		Description: "Mattermost access token",
		Regex:       "(?i)\\b(?:mattermost)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{26})\\b",
		Severity:    "high",
		Prefix:      "mattermost",
		MinEntropy:  3.0,
	},
	{
		ID:          "codecov",
		Description: "Codecov access token",
		Regex:       "(?i)\\b(?:codecov)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{32})\\b",
		Severity:    "high",
		Prefix:      "codecov",
		MinEntropy:  3.0,
	},
	{
		ID:          "confluent",
		Description: "Confluent secret key",
		Regex:       "(?i)\\b(?:confluent)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{64})\\b",
		Severity:    "critical",
		Prefix:      "confluent",
		MinEntropy:  3.0,
	},
	{
		ID:          "contentful",
		Description: "Contentful delivery token",
		Regex:       "(?i)\\b(?:contentful)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{43})\\b",
		Severity:    "critical",
		Prefix:      "contentful",
		MinEntropy:  3.0,
	},
	{
		ID:          "fastly",
		Description: "Fastly API token",
		Regex:       "(?i)\\b(?:fastly)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{32})\\b",
		Severity:    "critical",
		Prefix:      "fastly",
		MinEntropy:  3.0,
	},
	{
		ID:          "asana",
		Description: "Asana client secret",
		Regex:       "(?i)\\b(?:asana)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{32})\\b",
		Severity:    "high",
		Prefix:      "asana",
		MinEntropy:  3.0,
	},
	{
		ID:          "bitbucket_client",
		Description: "Bitbucket client secret",
		Regex:       "(?i)\\b(?:bitbucket)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{64})\\b",
		Severity:    "critical",
		Prefix:      "bitbucket",
		MinEntropy:  3.0,
	},
	{
		ID:          "discord_client",
		Description: "Discord client secret",
		Regex:       "(?i)\\b(?:discord)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9=_\\-]{32})\\b",
		Severity:    "high",
		Prefix:      "discord",
		MinEntropy:  3.0,
	},
	{
		ID:          "linkedin_client",
		Description: "LinkedIn client secret",
		Regex:       "(?i)\\b(?:linked[_-]?in)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{16})\\b",
		Severity:    "high",
		Prefix:      "linkedin",
		MinEntropy:  3.0,
	},
	{
		ID:          "mailgun",
		Description: "Mailgun private API token",
		Regex:       "(?i)\\b(?:mailgun)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}(key-[a-f0-9]{32})\\b",
		Severity:    "critical",
		Prefix:      "mailgun",
		MinEntropy:  3.0,
	},
	{
		ID:          "dropbox_long",
		Description: "Dropbox long-lived API token",
		Regex:       "(?i)\\b(?:dropbox)[\\s'\\\"]{0,3}(?:=|:)[\\x60'\\\"\\s=]{0,5}([a-z0-9]{11}AAAAAAAAAA[a-z0-9\\-_=]{43})\\b",
		Severity:    "critical",
		Prefix:      "dropbox",
		MinEntropy:  3.0,
	},
}

// multilineRules run against whole file content rather than per line.
var multilineRules = map[string]bool{"kubernetes_secret": true}

// bypassCodeCheck are rules whose shape is distinctive enough that the
// looks-like-code heuristic would only cause false negatives.
var bypassCodeCheck = map[string]bool{
	"airtable":            true,
	"algolia":             true,
	"asana":               true,
	"bitbucket_client":    true,
	"cloudflare":          true,
	"codecov":             true,
	"confluent":           true,
	"contentful":          true,
	"datadog":             true,
	"discord_client":      true,
	"dropbox":             true,
	"dropbox_long":        true,
	"fastly":              true,
	"gcp_service_account": true,
	"heroku":              true,
	"intercom":            true,
	"jfrog":               true,
	"jwt":                 true,
	"launchdarkly":        true,
	"linkedin_client":     true,
	"mailchimp":           true,
	"mailgun":             true,
	"mapbox":              true,
	"mattermost":          true,
	"netlify":             true,
	"okta":                true,
	"pgp_private_key":     true,
	"plaid":               true,
	"private_key_openssh": true,
	"private_key_pem":     true,
	"sentry":              true,
	"slack_webhook":       true,
	"sumologic":           true,
	"travisci":            true,
	"twitch":              true,
	"twitter_bearer":      true,
	"zendesk":             true,
}
